# Generated by Django 5.0.6 on 2024-05-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_experience_job_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('project_name', models.CharField(blank='', default='', max_length=254, verbose_name='Project Name')),
                ('project_description', models.CharField(blank='', default='', max_length=254, verbose_name='Description')),
                ('project_date', models.DateField(verbose_name='Project Date')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('project_date',),
            },
        ),
    ]
